name: Upload schema

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        paths:
            - 'schemas/latest'

concurrency: deploy

permissions:
    id-token: write
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        timeout-minutes: 10
        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::011833101604:role/doist-schemas-RoleCI-1P8IZE7IZUTXD
                  role-duration-seconds: 900
                  aws-region: us-east-1

            - name: Publish
              run: |
                  aws s3 cp schemas/latest/doist-card.json s3://doist-schemas-us-east-1-011833101604/doist-card.json
